# Document:
# http://simiki.org/docs/configuration.html

url: http://ruter.sundaystart.net
title: Ruter's Knowledge Wiki
keywords: knowledge, wiki, python, Ruter
description: It's a knowledge management wiki.
author: Ruter

root: /

theme: knowledge

